#Security

paladin.user.security_login:
    path: /login
    controller: Paladin\UserBundle\Controller\SecurityController::login

paladin.user.security_login_check:
    path: /login_check
    controller: Paladin\UserBundle\Controller\SecurityController::loginCheck

paladin.user.security_logout:
    path: /logout
    controller: Paladin\UserBundle\Controller\SecurityController::logout
    
#Resetting
    
paladin_user_resetting_request:
    path: /resetting/request
    controller: Paladin\UserBundle\Controller\ResettingController::request

paladin_user_resetting_send_email:
    path: /resetting/send-email
    controller: Paladin\UserBundle\Controller\ResettingController::sendEmail

paladin_user_resetting_check_email:
    path: /resetting/request
    controller: Paladin\UserBundle\Controller\ResettingController::checkEmail

paladin_user_resetting_reset:
    path: /resetting/reset/{token}
    controller: Paladin\UserBundle\Controller\ResettingController::reset

#Register
    
#paladin_user_resetting_request:
#    path: /resetting/request
#    controller: Paladin\UserBundle\Controller\ResettingController::request